language: python
python:
  - "3.7"

before_install:
  - pip install -q flit~=2.1
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g eclint

install:
  - flit install

script:
  - flake8 .
  - eclint check *.py sites/*.py
  - leech --help
  - python3 src/leech/ebook/cover.py && file -E output.png && rm output.png
  # - python3 src/leech/ebook/epub.py && file -E test.epub
  - flit build
  - ls -og dist/*
